version: "3.8"
services:
  mysqldb:
    image: mysql:latest
    restart: unless-stopped
    volumes:
      - mysql-data-2:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=root
    ports:
      - 3306:3306

volumes:
  mysql-data-2: